// <auto-generated />
using System;
using BackendBatch7.Domains;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendBatch7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240530082431_Init_department_table")]
    partial class Init_department_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendBatch7.Domains.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("Department_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("Updated_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 857, DateTimeKind.Local).AddTicks(7981),
                            Department_name = "Phát triển phần mềm",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 857, DateTimeKind.Local).AddTicks(7994),
                            Department_name = "Vận hành",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 857, DateTimeKind.Local).AddTicks(7996),
                            Department_name = "Hỗ trợ khách hàng",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BackendBatch7.Domains.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("Updated_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(167),
                            Email = "nguyenvanA@gmail.com",
                            First_name = "A",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 2,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(173),
                            Email = "nguyenvanB@gmail.com",
                            First_name = "B",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 3,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(175),
                            Email = "nguyenvanC@gmail.com",
                            First_name = "C",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 4,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(177),
                            Email = "nguyenvanD@gmail.com",
                            First_name = "D",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 5,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(178),
                            Email = "nguyenvanE@gmail.com",
                            First_name = "E",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 6,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(180),
                            Email = "nguyenvanF@gmail.com",
                            First_name = "F",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 7,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(181),
                            Email = "nguyenvanG@gmail.com",
                            First_name = "G",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 8,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(183),
                            Email = "nguyenvanH@gmail.com",
                            First_name = "H",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 9,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(184),
                            Email = "nguyenvanI@gmail.com",
                            First_name = "I",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 10,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(186),
                            Email = "nguyenvanJ@gmail.com",
                            First_name = "J",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 11,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(187),
                            Email = "nguyenvanK@gmail.com",
                            First_name = "K",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 12,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(189),
                            Email = "nguyenvanL@gmail.com",
                            First_name = "L",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 13,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(190),
                            Email = "nguyenvanM@gmail.com",
                            First_name = "M",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 14,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(192),
                            Email = "nguyenvanN@gmail.com",
                            First_name = "N",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 15,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(193),
                            Email = "nguyenvanO@gmail.com",
                            First_name = "O",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 16,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(194),
                            Email = "nguyenvanP@gmail.com",
                            First_name = "P",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 17,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(196),
                            Email = "nguyenvanQ@gmail.com",
                            First_name = "Q",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 18,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(197),
                            Email = "nguyenvanR@gmail.com",
                            First_name = "R",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 19,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(198),
                            Email = "nguyenvanS@gmail.com",
                            First_name = "S",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 20,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(200),
                            Email = "nguyenvanT@gmail.com",
                            First_name = "T",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 21,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(201),
                            Email = "nguyenvanU@gmail.com",
                            First_name = "U",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 22,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(203),
                            Email = "nguyenvanV@gmail.com",
                            First_name = "V",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 23,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(204),
                            Email = "nguyenvanW@gmail.com",
                            First_name = "W",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 24,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(205),
                            Email = "nguyenvanX@gmail.com",
                            First_name = "X",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 25,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(207),
                            Email = "nguyenvanY@gmail.com",
                            First_name = "Y",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 26,
                            Created_date = new DateTime(2024, 5, 30, 15, 24, 28, 858, DateTimeKind.Local).AddTicks(208),
                            Email = "nguyenvanZ@gmail.com",
                            First_name = "Z",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
