// <auto-generated />
using System;
using BackendBatch7.Domains;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendBatch7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240524025322_Init-db")]
    partial class Initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendBatch7.Domains.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("Updated_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9302),
                            Email = "nguyenvanA@gmail.com",
                            First_name = "A",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 2,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9316),
                            Email = "nguyenvanB@gmail.com",
                            First_name = "B",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 3,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9318),
                            Email = "nguyenvanC@gmail.com",
                            First_name = "C",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 4,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9320),
                            Email = "nguyenvanD@gmail.com",
                            First_name = "D",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 5,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9321),
                            Email = "nguyenvanE@gmail.com",
                            First_name = "E",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 6,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9323),
                            Email = "nguyenvanF@gmail.com",
                            First_name = "F",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 7,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9324),
                            Email = "nguyenvanG@gmail.com",
                            First_name = "G",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 8,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9326),
                            Email = "nguyenvanH@gmail.com",
                            First_name = "H",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 9,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9327),
                            Email = "nguyenvanI@gmail.com",
                            First_name = "I",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 10,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9329),
                            Email = "nguyenvanJ@gmail.com",
                            First_name = "J",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 11,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9330),
                            Email = "nguyenvanK@gmail.com",
                            First_name = "K",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 12,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9332),
                            Email = "nguyenvanL@gmail.com",
                            First_name = "L",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 13,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9333),
                            Email = "nguyenvanM@gmail.com",
                            First_name = "M",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 14,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9335),
                            Email = "nguyenvanN@gmail.com",
                            First_name = "N",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 15,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9336),
                            Email = "nguyenvanO@gmail.com",
                            First_name = "O",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 16,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9338),
                            Email = "nguyenvanP@gmail.com",
                            First_name = "P",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 17,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9339),
                            Email = "nguyenvanQ@gmail.com",
                            First_name = "Q",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 18,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9340),
                            Email = "nguyenvanR@gmail.com",
                            First_name = "R",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 19,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9342),
                            Email = "nguyenvanS@gmail.com",
                            First_name = "S",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 20,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9343),
                            Email = "nguyenvanT@gmail.com",
                            First_name = "T",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 21,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9345),
                            Email = "nguyenvanU@gmail.com",
                            First_name = "U",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 22,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9346),
                            Email = "nguyenvanV@gmail.com",
                            First_name = "V",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 23,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9348),
                            Email = "nguyenvanW@gmail.com",
                            First_name = "W",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 24,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9349),
                            Email = "nguyenvanX@gmail.com",
                            First_name = "X",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 25,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9422),
                            Email = "nguyenvanY@gmail.com",
                            First_name = "Y",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        },
                        new
                        {
                            Id = 26,
                            Created_date = new DateTime(2024, 5, 24, 9, 53, 22, 77, DateTimeKind.Local).AddTicks(9423),
                            Email = "nguyenvanZ@gmail.com",
                            First_name = "Z",
                            IsDeleted = false,
                            Last_name = "Nguyen Van"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
